services:
 
  mongodb:
    image: mongo:latest
    container_name: movielens_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - movielens-net

  redis:
    image: redis:alpine
    container_name: movielens_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - movielens-net

  api:
    container_name: movielens_api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - WORKER_ADDR=worker:8081
    depends_on:
      - mongodb
      - redis
    networks:
      - movielens-net

  worker:
   
    build:
      context: .
      dockerfile: worker/Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - movielens-net

volumes:
  mongo_data:

networks:
  movielens-net:
    driver: bridge