version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: movielens_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - movielens-net

  redis:
    image: redis:alpine
    container_name: movielens_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - movielens-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: movielens_frontend
    restart: always
    ports:
      - "80:80"  
    depends_on:
      - api     
    networks:
      - movielens-net

  api:
    container_name: movielens_api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - MONGO_URI=mongodb://mongodb:27017
      - WORKER_ADDRS=worker-1:8081,worker-2:8081,worker-3:8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongodb
      - redis
      - worker-1
      - worker-2
      - worker-3
    networks:
      - movielens-net

  worker-1:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker-1
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - NODE_ID=1
    depends_on:
      - mongodb
    networks:
      - movielens-net

  worker-2:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker-2
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - NODE_ID=2
    depends_on:
      - mongodb
    networks:
      - movielens-net

  worker-3:
    build:
      context: .
      dockerfile: worker/Dockerfile
    container_name: worker-3
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - NODE_ID=3
    depends_on:
      - mongodb
    networks:
      - movielens-net

volumes:
  mongo_data:

networks:
  movielens-net:
    driver: bridge